version: '3'

services:
    php:
        image: php:7.4-cli-alpine
        working_dir: /app
        volumes:
            - ./:/app:cached
        user: ${HOST_UID}:${HOST_GID}

    composer:
        image: composer:latest
        volumes:
            - ./:/app:cached
        user: ${HOST_UID}:${HOST_GID}
